"""Generate public/serverless defaults from the API's canonical Typst layout."""
from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def generated_layouts() -> dict[Path, str]:
    canonical = (ROOT / "api/app/resume_template.typ").read_text(encoding="utf-8")
    master = ROOT / "data/profile.example/templates/master.typ"
    prefix, _ = canonical.split("// Header", 1)
    _, body = master.read_text(encoding="utf-8").split("// Header", 1)
    return {
        ROOT / "data/profile.example/templates/base_resume.typ": canonical,
        master: prefix.replace("{{LAYOUT_DENSITY}}", "comfortable") + "// Header" + body,
        ROOT / "frontend/api/stateless/resume-template.ts": (
            "// Generated by scripts/sync_resume_layout.py; edit api/app/resume_template.typ.\n"
            "export const DEFAULT_RESUME_TEMPLATE = " + json.dumps(canonical) + ";\n"
        ),
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if generated defaults are stale")
    args = parser.parse_args()
    stale = []
    for path, expected in generated_layouts().items():
        if path.exists() and path.read_text(encoding="utf-8") == expected:
            continue
        if args.check:
            stale.append(str(path.relative_to(ROOT)))
        else:
            path.write_text(expected, encoding="utf-8")
    if stale:
        parser.exit(1, "Stale resume layouts; run python scripts/sync_resume_layout.py:\n" + "\n".join(stale) + "\n")


if __name__ == "__main__":
    main()
